sudo: required
services:
  - docker

before_install:
  - docker build -t titanxl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run titanxl/react-test npm test -- --watchAll=false

after_success:
  - docker build -t titanxl/multi-client ./client
  - docker build -t titanxl/multi-nginx ./nginx
  - docker build -t titanxl/multi-server ./server
  - docker build -t titanxl/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push titanxl/multi-client
  - docker push titanxl/multi-nginx
  - docker push titanxl/multi-server
  - docker push titanxl/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-810433389795
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
